In [31]:
import numpy as np
houses = []
houses = np.genfromtxt("Housing Price data set.csv",delimiter=",",skip_header=1,skip_footer = 146,usecols = (1,2,3,4))
houses
#1st column is price 2nd,3rd and 4th are input data 
#Taking first 400 samples as training data

array([[4.200e+04, 5.850e+03, 3.000e+00, 1.000e+00],
       [3.850e+04, 4.000e+03, 2.000e+00, 1.000e+00],
       [4.950e+04, 3.060e+03, 3.000e+00, 1.000e+00],
       ...,
       [8.075e+04, 6.660e+03, 4.000e+00, 2.000e+00],
       [8.290e+04, 7.000e+03, 3.000e+00, 1.000e+00],
       [8.500e+04, 7.231e+03, 3.000e+00, 1.000e+00]])

In [32]:
houses.shape

(400, 4)

In [33]:
house_Y = houses[:,[0]]
house_Y

array([[ 42000.],
       [ 38500.],
       [ 49500.],
       [ 60500.],
       [ 61000.],
       [ 66000.],
       [ 66000.],
       [ 69000.],
       [ 83800.],
       [ 88500.],
       [ 90000.],
       [ 30500.],
       [ 27000.],
       [ 36000.],
       [ 37000.],
       [ 37900.],
       [ 40500.],
       [ 40750.],
       [ 45000.],
       [ 45000.],
       [ 48500.],
       [ 65900.],
       [ 37900.],
       [ 38000.],
       [ 42000.],
       [ 42300.],
       [ 43500.],
       [ 44000.],
       [ 44500.],
       [ 44900.],
       [ 45000.],
       [ 48000.],
       [ 49000.],
       [ 51500.],
       [ 61000.],
       [ 61000.],
       [ 61700.],
       [ 67000.],
       [ 82000.],
       [ 54500.],
       [ 66500.],
       [ 70000.],
       [ 82000.],
       [ 92000.],
       [ 38000.],
       [ 44000.],
       [ 41000.],
       [ 43000.],
       [ 48000.],
       [ 54800.],
       [ 55000.],
       [ 57000.],
       [ 68000.],
       [ 95000.],
       [ 38000.],
       [ 2

In [35]:
house_X = houses[:,1:4]
house_X

array([[5.850e+03, 3.000e+00, 1.000e+00],
       [4.000e+03, 2.000e+00, 1.000e+00],
       [3.060e+03, 3.000e+00, 1.000e+00],
       ...,
       [6.660e+03, 4.000e+00, 2.000e+00],
       [7.000e+03, 3.000e+00, 1.000e+00],
       [7.231e+03, 3.000e+00, 1.000e+00]])

In [39]:
X_transpose = house_X.transpose()
X_transpose

array([[5.850e+03, 4.000e+03, 3.060e+03, ..., 6.660e+03, 7.000e+03,
        7.231e+03],
       [3.000e+00, 2.000e+00, 3.000e+00, ..., 4.000e+00, 3.000e+00,
        3.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 2.000e+00, 1.000e+00,
        1.000e+00]])

In [55]:
X_T_X = np.dot(X_transpose,house_X)
X_T_X

array([[1.14233806e+10, 5.90357700e+06, 2.60740800e+06],
       [5.90357700e+06, 3.72200000e+03, 1.56600000e+03],
       [2.60740800e+06, 1.56600000e+03, 7.59000000e+02]])

In [44]:
X_T_Y = np.dot(X_transpose,house_Y)
X_T_Y

array([[1.40881413e+11],
       [7.97748110e+07],
       [3.60747290e+07]])

In [47]:
X_T_X_inverse = np.linalg.inv(X_T_X)
X_T_X_inverse

array([[ 5.24348738e-10, -5.59487140e-07, -6.46948923e-07],
       [-5.59487140e-07,  2.63378773e-03, -3.51212166e-03],
       [-6.46948923e-07, -3.51212166e-03,  1.07863535e-02]])

In [48]:
theta = np.dot(X_T_X_inverse,X_T_Y)
theta

array([[5.89950301e+00],
       [4.58974259e+03],
       [1.77928600e+04]])

In [63]:
#testing on data
test_houses = np.genfromtxt("Housing Price data set.csv",delimiter=",",skip_header=401,usecols = (1,2,3,4))
X_test = test_houses[:,1:4]
Y_test = test_houses[:,[0]]
Y_test

array([[ 92500.],
       [ 76000.],
       [ 77500.],
       [ 80000.],
       [ 80000.],
       [ 86000.],
       [ 87000.],
       [ 87500.],
       [ 89000.],
       [ 89900.],
       [ 90000.],
       [ 95000.],
       [112000.],
       [ 31900.],
       [ 52000.],
       [ 90000.],
       [100000.],
       [ 91700.],
       [174500.],
       [ 94700.],
       [ 68000.],
       [ 80000.],
       [ 61100.],
       [ 62900.],
       [ 65500.],
       [ 66000.],
       [ 49500.],
       [ 50000.],
       [ 53500.],
       [ 58550.],
       [ 64500.],
       [ 65000.],
       [ 69000.],
       [ 73000.],
       [ 75000.],
       [ 75000.],
       [132000.],
       [ 60000.],
       [ 65000.],
       [ 69000.],
       [ 51900.],
       [ 57000.],
       [ 65000.],
       [ 79500.],
       [ 72500.],
       [104900.],
       [114900.],
       [120000.],
       [ 58000.],
       [ 67000.],
       [ 67000.],
       [ 69000.],
       [ 73000.],
       [ 73500.],
       [ 74900.],
       [ 7

In [53]:
Y_predict = np.dot(X_test,theta)
Y_predict

array([[ 75277.40509141],
       [ 77578.21126467],
       [ 71826.19583152],
       [ 69082.92693263],
       [ 92881.41027882],
       [ 90061.51859369],
       [ 70498.80765464],
       [ 69436.89711313],
       [ 88291.66769118],
       [ 88291.66769118],
       [ 84657.6148747 ],
       [ 87701.71739035],
       [ 86875.78696918],
       [ 62829.45374376],
       [ 66168.53140983],
       [ 69318.90705296],
       [ 97489.03391789],
       [ 66793.99051826],
       [ 98190.96298634],
       [ 66959.10584962],
       [ 87383.25601744],
       [ 61861.93525039],
       [ 51620.39802788],
       [ 48552.65646353],
       [ 54216.17935156],
       [ 43903.91884581],
       [ 58357.7012163 ],
       [ 47691.39977718],
       [ 47502.61568091],
       [ 52800.29862955],
       [ 47738.59580125],
       [ 62947.44380393],
       [ 67195.08596995],
       [ 94285.67453722],
       [ 81117.91306969],
       [ 85212.05636795],
       [ 95371.07130122],
       [ 52328.33838888],
       [ 631

In [73]:
#Root Mean Square Error
error_0_rms = np.mean([(Y_predict[i] - Y_test[i]) ** 2 for i in range(146)]) ** 0.5
error_0_rms 

18992.36182746691

In [76]:
#Mean Absolute Percent Error
MAPE_0 = np.mean([abs((Y_predict[i] - Y_test[i])/Y_test[i]) for i in range(146)])*100
MAPE_0

18.980113117933918

In [57]:
#Now coming to Normal Equation with Regularization
#here theta = (X_T_X + lambda(.)L).(X_T).(Y)
lambda_ = 1500
L = np.zeros(shape = (3,3))
L[1,1] = 1
L[2,2] = 1
L = lambda_ * L
L

array([[   0.,    0.,    0.],
       [   0., 1500.,    0.],
       [   0.,    0., 1500.]])

In [59]:
theta_1 = np.dot(np.linalg.inv(X_T_X + L),X_T_Y)
theta_1

array([[  10.32882241],
       [3012.14281902],
       [1959.38873522]])

In [60]:
Y_predict_1 = np.dot(X_test,theta_1)
Y_predict_1

array([[ 87532.39127921],
       [ 91560.63202063],
       [ 81490.03016708],
       [ 76687.12774462],
       [ 84137.57667819],
       [ 84224.08058334],
       [ 79166.04512396],
       [ 77306.85708946],
       [ 81125.43385917],
       [ 81125.43385917],
       [103955.21891729],
       [ 80092.55161778],
       [ 78646.51647984],
       [ 65738.5759859 ],
       [ 42392.34980708],
       [ 77100.28064118],
       [126420.40766751],
       [ 77703.22566702],
       [ 93433.51685069],
       [ 72968.75167562],
       [113750.8158915 ],
       [ 64044.64911002],
       [ 46113.8133995 ],
       [ 40742.82574428],
       [ 50658.49526162],
       [ 37627.39470112],
       [ 62933.00961516],
       [ 44258.49869084],
       [ 43927.9763736 ],
       [ 48179.57788228],
       [ 44341.12927015],
       [ 65945.15243418],
       [ 73381.90457218],
       [125835.53811575],
       [ 97757.92546896],
       [ 70710.10754013],
       [ 93520.02075584],
       [ 47353.27208917],
       [ 663

In [74]:
#Root Mean Square Error
error_1 = np.mean([(Y_predict_1[i] - Y_test[i]) ** 2 for i in range(146)]) ** 0.5
error_1 

25472.065765004267

In [77]:
#Mean Absolute Percent Error
MAPE_1 = np.mean([abs((Y_predict_1[i] - Y_test[i])/Y_test[i]) for i in range(146)])*100
MAPE_1

27.16072516910385

In [ ]:
''' After Comparing RMS Error value and MAP Error of above two models(i.e. Normal Equation with and 
    without Reguralisation with lambda value 1500),we can say that here Simple Normal Equation Model 
    is working better than the latter one.[We can change the value of lambda to view better results ]'''  